main: itz.lirdev.LirBroadcast
version: "2.1.1"
name: LirBroadcast
author: LirDev
api-version: 1.16
commands:
  lirbroadcast:
    permission: lirbroadcast.admin
    aliases:
      - lbc
  notification:
    aliases:
      - notify

permissions:
  lirbroadcast.admin:
    default: op
  lirbroadcast.alert:
    default: op

folia-supported: true
